# Generated by Django 2.2.1 on 2019-06-27 21:30

from django.db import migrations
import colorinput.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggsonomy', '0007_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorinput.models.ColorField(default='d0d0d0'),
        ),
    ]
