# Generated by Django 2.1.4 on 2019-02-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggsonomy', '0002_auto_20190121_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagset',
            name='content_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='tagset',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
