# Generated by Django 2.2.1 on 2019-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggsonomy', '0006_tag__inclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='d0d0d0', max_length=6),
        ),
    ]
