# Generated by Django 2.1.4 on 2019-02-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggsonomy', '0003_auto_20190204_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagset',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='tagset',
            unique_together={('content_type', 'object_id')},
        ),
    ]
