# Generated by Django 2.1.4 on 2019-03-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_taggsonomy', '0004_auto_20190204_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='_exclusions',
            field=models.ManyToManyField(related_name='_tag__exclusions_+', to='django_taggsonomy.Tag'),
        ),
    ]
