# Generated by Django 2.2.1 on 2019-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_taggsonomy', '0005_tag__exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='_inclusions',
            field=models.ManyToManyField(to='django_taggsonomy.Tag'),
        ),
    ]
